/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * To learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.5/samples
 */

plugins {
    `java-library`
    id("io.papermc.paperweight.userdev") version "1.5.10"
}

group = "me.lunaiskey.cakeclicker"
version = "0.1"
//description = "Test plugin for paperweight-userdev"


dependencies {
    paperweight.paperDevBundle("1.19.4-R0.1-SNAPSHOT")
    //compileOnly("com.github.retrooper.packetevents:spigot:2.2.0")
}

repositories {
    mavenCentral()
    maven {
        url = uri("https://repo.codemc.io/repository/maven-releases/")
    }
}

tasks {
    // Configure reobfJar to run when invoking the build task
    assemble {
        dependsOn(reobfJar)
    }

    compileJava {
        options.encoding = Charsets.UTF_8.name() // We want UTF-8 for everything

        // Set the release flag. This configures what version bytecode the compiler will emit, as well as what JDK APIs are usable.
        // See https://openjdk.java.net/jeps/247 for more information.
        options.release.set(17)
    }
    javadoc {
        options.encoding = Charsets.UTF_8.name() // We want UTF-8 for everything
    }
    processResources {
        filteringCharset = Charsets.UTF_8.name() // We want UTF-8 for everything
        val props = mapOf(
                //"name" to project.name,
                "version" to project.version,
                //"description" to project.description,
                //"apiVersion" to "1.20"
        )
        inputs.properties(props)
        filesMatching("plugin.yml") {
            expand(props)
        }
    }

    /*
    reobfJar {
      // This is an example of how you might change the output location for reobfJar. It's recommended not to do this
      // for a variety of reasons, however it's asked frequently enough that an example of how to do it is included here.
      outputJar.set(layout.buildDirectory.file("libs/PaperweightTestPlugin-${project.version}.jar"))
    }
     */
}
